### ISSUE TITLE
error NSPOSIXErrorDomain / 25

### ISSUE THREAD

**Issue by duanruiying** [brenwell/EvenBetterAuthorizationSample#3]
=== In this method “connectAndExecuteCommandBlock”，connectReplyEndpoint Always nil  ===
- (void)connectAndExecuteCommandBlock:(void(^)(NSError *))commandBlock {
        if (connectReplyEndpoint == nil) 
}
=== error: error NSPOSIXErrorDomain / 25  ===

**Comment by duanruiying** [comment]
The connection to service named com.blackwellapps.BrokerHelperwas invalidated.

**Comment by brenwell** [comment]
Hey, is this a question?
